version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.9.0
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  preload:
    image: curlimages/curl
    depends_on: [ ollama ]
    entrypoint: >
      sh -c "
        sleep 10 &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"mistral:7b\"}'
      "
    restart: "no"

  app:
    image: python:3.12-slim
    depends_on:
      - ollama
    working_dir: /app
    volumes:
      - ./app:/app
      - ./documents:/documents
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    command: >
      bash -c "
        pip install --no-cache-dir -r requirements.txt &&
        sleep 5 &&
        python main.py
      "

volumes:
  ollama-data: