version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.9.0
    ports:
      - "11434:11434"
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ollama-data:/root/.ollama
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  mistral-7b-preload:
    image: curlimages/curl
    depends_on: [ ollama ]
    entrypoint: >
      sh -c "
        sleep 10 &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"mistral:7b\"}'
      "
    restart: "no"
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  flask:
    image: python:3.12-slim
    depends_on:
      - ollama
    working_dir: /app
    volumes:
      - ./app:/app
      - ./documents:/documents
      - chroma-data:/root/.chromadb
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - TZ=Asia/Kolkata
    command: >
      bash -c "
        pip install --no-cache-dir -r requirements.txt &&
        sleep 5 &&
        python main.py
      "

volumes:
  ollama-data:
  chroma-data:
